// Gramatica del lenguaje Delta

comment = r'[/][/].*|[/][*](.|\n)*?[*][/]'

program = expression EOF
expression = multiplicative (('+' / '-') multiplicative)* 
multiplicative = unary (('*' / '/' / '%') unary)*
unary = ('+' / '-' / '!')* primary
primary = decimal / boolean / parenthesis
decimal = r'\d+'
boolean = 'true' / 'false'

// parenthesis = r'[(]' expression r'[)]'
parenthesis = '(' expression ')'